import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { SanityDocument, createClient } from "next-sanity";
import Navbar from "@/components/navigation/navbar";
import Footer from "@/components/navigation/footer";

const inter = Inter({ subsets: ["latin"] });

const sanityClient = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
  useCdn: true, // `false` if you want to bypass the edge cache
  apiVersion: process.env.SANITY_API_VERSION, // use a current date to target the latest API version
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CONTENT_QUERY = `  
*[_type=="layout"]{
  navbar,
  hero,
  footer{
    contactBar{
      contactList[]{
        contactIcon{
          "url": asset->url
        },
        contactLink,
        contactBackground,
        contactTextColor
      },
    },
    seperator{
      "url": asset->url
    }
  }
}
`;
const STYLE_QUERY = `
*[_type=="style"]{
  theme
}
`;


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const style = await sanityClient.fetch(STYLE_QUERY);
  const layout = await sanityClient.fetch(CONTENT_QUERY);

  const { navbar, hero, footer } = layout[0];
  const { theme } = style[0];
  return (
    <html lang="en">
      <body>
        <Navbar  {...navbar} />
        <main>{children}</main>
        <Footer footer={footer} theme={theme} />
      </body>
    </html>
  );
}
